#!/usr/bin/env python3
"""Build a seed MIGRATION_LEDGER.yml from cpp+rust symbol manifests.

Every C++ symbol in cpp_symbol_manifest.json becomes a row, populated
verbatim from the manifest under `cpp:`, with a best-effort Rust
candidate list under `rust:`. All seed rows start as:

    status: uncertain
    migration_type: unknown
    confidence: low

The Rust candidate heuristic is intentionally weak — it matches only on
normalized name shapes. Per design.md §3 and §6, name similarity is
never sufficient evidence to flip a row to `migrated`. The seed just
gives auditors a starting list to verify or replace.

Usage:
    python3 scripts/ledger/build_seed.py [--out PATH] [--cpp PATH] [--rust PATH]

Without flags, writes to apps/poketibia/forgottenserver-rust/MIGRATION_LEDGER.yml
and reads cpp_symbol_manifest.json / rust_symbol_manifest.json from the
same directory.
"""
from __future__ import annotations

import argparse
import datetime
import json
import os
import re
import sys
from collections import defaultdict
from typing import Any

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import ledger_io  # noqa: E402

DEFAULT_ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir))


# ---------------------------------------------------------------------------
# Id generation
# ---------------------------------------------------------------------------

_SLUG_PUNCT = re.compile(r"[^a-z0-9]+")


def _slug(s: str) -> str:
    s = s.replace("::", "-")
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", s)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s)
    s = s.lower()
    s = _SLUG_PUNCT.sub("-", s)
    return s.strip("-")


def _id_for(cpp: dict[str, Any]) -> str:
    stem = os.path.splitext(os.path.basename(cpp["file"]))[0]
    kind = cpp["kind"]
    sym = _slug(cpp["qualified_name"])
    return f"{_slug(stem)}__{kind}__{sym}"


# ---------------------------------------------------------------------------
# Rust candidate heuristic
# ---------------------------------------------------------------------------

_CAMEL_RE = re.compile(r"([a-z0-9])([A-Z])")


def _normalize(name: str) -> str:
    name = name.replace("::", " ")
    name = _CAMEL_RE.sub(r"\1_\2", name)
    return name.lower().strip()


def _index_rust(rust_symbols: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """Bucket rust symbols by normalized last segment of qualified_name."""
    idx: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for s in rust_symbols:
        qn = s.get("qualified_name") or ""
        if not qn:
            continue
        last = qn.split("::")[-1]
        key = _normalize(last)
        if key:
            idx[key].append(s)
    return idx


def _candidates(cpp: dict[str, Any], rust_idx: dict[str, list[dict[str, Any]]]) -> list[dict[str, Any]]:
    qn = cpp.get("qualified_name") or ""
    if not qn:
        return []
    last = qn.split("::")[-1]
    key = _normalize(last)
    bucket = rust_idx.get(key, [])
    # Keep at most three candidates, prefer ones whose qualified_name
    # contains a normalized form of the C++ owner (class).
    if not bucket:
        return []
    owner = ""
    if "::" in qn:
        owner = _normalize(qn.split("::")[-2])
    scored: list[tuple[int, dict[str, Any]]] = []
    for r in bucket:
        rn = _normalize(r["qualified_name"])
        score = 0
        if owner and owner in rn:
            score += 2
        if rn.endswith(key):
            score += 1
        scored.append((score, r))
    scored.sort(key=lambda t: (-t[0], t[1]["qualified_name"]))
    out = [r for _, r in scored[:3]]
    return out


def _rust_entry(r: dict[str, Any]) -> dict[str, Any]:
    return {
        "file": r["file"],
        "symbol": r["qualified_name"],
        "signature": r.get("signature", ""),
        "kind": r["kind"],
        "body_hash": r.get("body_hash", ""),
    }


# ---------------------------------------------------------------------------
# Seed assembly
# ---------------------------------------------------------------------------

HEADER = """\
MIGRATION_LEDGER.yml — per-symbol migration audit (authoritative)

Generated by scripts/ledger/build_seed.py from the symbol manifests.
DO NOT EDIT BY HAND for the cpp.* fields — they are copied verbatim
from cpp_symbol_manifest.json and a build_seed.py rerun will overwrite
manual changes. The rust.*, status, evidence, etc. fields are owned by
the audit subagents.

Schema and rules: see openspec/changes/forgottenserver-migration-ledger-
symbol-audit/design.md.

Companion files (unchanged):
  - MIGRATION.md             (per-file narrative tracker)
  - MIGRATION_DELTA.md       (architectural-parity change deltas)
  - DEPENDENCY_GRAPH.md      (crate-layer assignments)
  - AI_MIGRATION_CONTEXT.md  (rules of engagement)
  - intentional_differences.yml  (recorded, justified divergences)

Allowed status values:
  migrated, migrated_with_changes, partial, missing,
  intentionally_removed, obsolete, uncertain, needs_review,
  output_verified

Allowed migration_type values:
  direct, renamed, split, merged, redesigned, removed, unknown

Run `python3 scripts/ledger/validate.py` to check this file.
"""


def build_doc(cpp_symbols: list[dict[str, Any]], rust_symbols: list[dict[str, Any]]) -> dict[str, Any]:
    rust_idx = _index_rust(rust_symbols)
    seen_ids: set[str] = set()
    symbols: list[dict[str, Any]] = []
    for cpp in cpp_symbols:
        sid = _id_for(cpp)
        # Disambiguate duplicate ids (overloads, multiple constants in const.h, etc.)
        base = sid
        n = 2
        while sid in seen_ids:
            sid = f"{base}--{n}"
            n += 1
        seen_ids.add(sid)
        rust_cands = [_rust_entry(r) for r in _candidates(cpp, rust_idx)]
        symbols.append({
            "id": sid,
            "cpp": {
                "file": cpp["file"],
                "symbol": cpp["qualified_name"],
                "signature": cpp.get("signature", ""),
                "kind": cpp["kind"],
                "body_hash": cpp.get("body_hash", ""),
            },
            "rust": rust_cands,
            "status": "uncertain",
            "migration_type": "unknown",
            "confidence": "low",
            "evidence": [],
            "semantic_differences": [],
            "risks": [],
            "tests_required": [],
            "differential_scenarios": [],
            "notes": "",
        })
    return {
        "version": 2,
        "schema": "per-symbol",
        "last_updated": datetime.date.today().isoformat(),
        "seed_source": "build_seed.py from cpp_symbol_manifest.json",
        "symbols": symbols,
    }


# ---------------------------------------------------------------------------
# C++ directory scanner (--include-dir)
# ---------------------------------------------------------------------------

import hashlib
import struct as _struct


def _body_hash(text: str) -> str:
    """16-char hex hash matching the convention in cpp_symbol_manifest.json."""
    digest = hashlib.md5(text.encode("utf-8")).digest()
    val = _struct.unpack("<Q", digest[:8])[0]
    return format(val, "016x")


def _scan_cpp_directory(dir_path: str, rel_prefix: str) -> list[dict[str, Any]]:
    """Extract C++ symbols from all .h and .cpp files in *dir_path*.

    Returns a list of dicts in the same shape as cpp_symbol_manifest.json
    entries so they can be appended directly to the manifest.
    """
    CPP_SRC = os.path.abspath(os.path.join(DEFAULT_ROOT, "..", "forgottenserver", "src"))

    results: list[dict[str, Any]] = []

    files = sorted(
        f for f in os.listdir(dir_path) if f.endswith(".h") or f.endswith(".cpp")
    )

    for fname in files:
        fpath = os.path.join(dir_path, fname)
        rel_file = rel_prefix + "/" + fname  # e.g. "src/http/session.h"
        with open(fpath, "r", encoding="utf-8", errors="replace") as fh:
            content = fh.read()
        results.extend(_parse_symbols(content, rel_file))

    return results


_NS_OPEN  = re.compile(r"^namespace\s+([\w:]+)\s*\{")
_NS_CLOSE = re.compile(r"^\}\s*//\s*namespace")
_CLASS_DEF = re.compile(r"^(class|struct)\s+(\w+)\b")
_PUBLIC    = re.compile(r"^\s*public\s*:")
_PRIVATE   = re.compile(r"^\s*private\s*:")
_FUNC_DECL = re.compile(
    r"^\s*(?:(?:static|explicit|inline|virtual|override|final)\s+)*"
    r"([\w:<>&*, \t]+?)\s+"        # return type (greedy-ish)
    r"(\w+)\s*\("                  # name(
    r"([^)]*)\)"                   # params)
    r"[^{;]*;"                     # ; no body
)


def _normalize_ns(stack: list[str]) -> str:
    return "::".join(stack)


def _parse_symbols(content: str, rel_file: str) -> list[dict[str, Any]]:
    """Regex-based C++ symbol extractor for the http subdirectory files."""
    lines = content.splitlines()
    symbols: list[dict[str, Any]] = []
    ns_stack: list[str] = []        # current namespace components
    class_name: str | None = None   # current class/struct name
    visibility: str = "public"      # current visibility
    brace_depth: int = 0
    class_brace_depth: int = -1     # brace depth when class opened

    for lineno, raw in enumerate(lines, start=1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("//"):
            continue

        # Track brace depth
        opens  = raw.count("{")
        closes = raw.count("}")
        brace_depth += opens - closes

        # Namespace open
        m = _NS_OPEN.match(stripped)
        if m:
            for part in m.group(1).split("::"):
                ns_stack.append(part)
            continue

        # Namespace close
        if _NS_CLOSE.match(stripped):
            if ns_stack:
                ns_stack.pop()
            continue

        # Class/struct declaration
        m = _CLASS_DEF.match(stripped)
        if m and class_name is None and "{" in raw:
            kind_kw = m.group(1)
            class_name = m.group(2)
            class_brace_depth = brace_depth - (opens - closes) + opens - closes
            visibility = "public" if kind_kw == "struct" else "private"
            ns = _normalize_ns(ns_stack)
            qname = f"{ns}::{class_name}" if ns else class_name
            symbols.append({
                "file": rel_file,
                "kind": kind_kw,
                "qualified_name": qname,
                "signature": stripped.split("{")[0].strip(),
                "visibility": "public",
                "line_start": lineno,
                "line_end": lineno,
                "dependencies": [],
                "behavior_summary": f"{kind_kw.capitalize()} {qname}",
                "risk_level": "medium",
                "body_hash": _body_hash(stripped),
                "notes": "",
            })
            continue

        # Visibility change inside class
        if class_name is not None:
            if _PUBLIC.match(stripped):
                visibility = "public"
                continue
            if _PRIVATE.match(stripped):
                visibility = "private"
                continue

        # Class closed (brace_depth dropped to class_brace_depth - 1)
        if class_name is not None and brace_depth < class_brace_depth:
            class_name = None
            class_brace_depth = -1
            visibility = "public"
            continue

        # Function / method declaration (ends with ";", no "{")
        if ";" in stripped and "(" in stripped and "{" not in stripped:
            m = _FUNC_DECL.match(raw)
            if m:
                ret_type = m.group(1).strip()
                func_name = m.group(2)
                params = m.group(3).strip()
                ns = _normalize_ns(ns_stack)
                if class_name:
                    owner = f"{ns}::{class_name}" if ns else class_name
                    qname = f"{owner}::{func_name}"
                    kind = "method"
                else:
                    qname = f"{ns}::{func_name}" if ns else func_name
                    kind = "free_function"
                sig = f"{ret_type} {qname}({params})"
                symbols.append({
                    "file": rel_file,
                    "kind": kind,
                    "qualified_name": qname,
                    "signature": sig,
                    "visibility": visibility if class_name else "free",
                    "line_start": lineno,
                    "line_end": lineno,
                    "dependencies": [],
                    "behavior_summary": f"Function {qname}",
                    "risk_level": "medium",
                    "body_hash": _body_hash(sig),
                    "notes": "",
                })

    return symbols


def _append_include_dir(
    cpp_manifest_path: str,
    ledger_path: str,
    rust_manifest_path: str,
    include_dir: str,
) -> int:
    """Append symbols from *include_dir* (relative to forgottenserver/src) to
    cpp_symbol_manifest.json and MIGRATION_LEDGER.yml.

    Only symbols whose `file` is NOT already in the manifest are added — so
    this is safe to re-run.
    """
    # Resolve the C++ source directory
    cpp_src = os.path.abspath(os.path.join(DEFAULT_ROOT, "..", "forgottenserver", "src"))
    dir_path = os.path.join(cpp_src, include_dir.lstrip("src/").lstrip("/"))
    rel_prefix = include_dir.rstrip("/")  # e.g. "src/http"

    new_syms = _scan_cpp_directory(dir_path, rel_prefix)
    if not new_syms:
        print(f"No symbols found in {dir_path}")
        return 0

    # --- Append to cpp_symbol_manifest.json ---------------------------------
    with open(cpp_manifest_path, "r", encoding="utf-8") as f:
        existing_manifest: list[dict] = json.load(f)

    existing_files = {e["file"] for e in existing_manifest}
    new_manifest = [s for s in new_syms if s["file"] not in existing_files]

    if not new_manifest:
        print("All http symbols already present in cpp_symbol_manifest.json")
    else:
        existing_manifest.extend(new_manifest)
        with open(cpp_manifest_path, "w", encoding="utf-8") as f:
            json.dump(existing_manifest, f, indent=2)
        print(f"Appended {len(new_manifest)} symbols to cpp_symbol_manifest.json")

    # --- Append symbol rows to MIGRATION_LEDGER.yml -------------------------
    with open(rust_manifest_path, "r", encoding="utf-8") as f:
        rust_syms: list[dict] = json.load(f)
    rust_idx = _index_rust(rust_syms)

    doc = ledger_io.load(open(ledger_path).read())
    existing_ids = {s["id"] for s in doc.get("symbols", [])}
    existing_ledger_files = {s["cpp"]["file"] for s in doc.get("symbols", [])}

    seen_ids: set[str] = set(existing_ids)
    new_rows: list[dict] = []
    for cpp in new_manifest:
        if cpp["file"] in existing_ledger_files:
            continue
        sid = _id_for(cpp)
        base = sid
        n = 2
        while sid in seen_ids:
            sid = f"{base}--{n}"
            n += 1
        seen_ids.add(sid)
        rust_cands = [_rust_entry(r) for r in _candidates(cpp, rust_idx)]
        new_rows.append({
            "id": sid,
            "cpp": {
                "file": cpp["file"],
                "symbol": cpp["qualified_name"],
                "signature": cpp.get("signature", ""),
                "kind": cpp["kind"],
                "body_hash": cpp.get("body_hash", ""),
            },
            "rust": rust_cands,
            "status": "uncertain",
            "migration_type": "unknown",
            "confidence": "low",
            "evidence": [],
            "semantic_differences": [],
            "risks": [],
            "tests_required": [],
            "differential_scenarios": [],
            "notes": "",
        })

    if not new_rows:
        print("All http ledger rows already present in MIGRATION_LEDGER.yml")
        return 0

    doc["symbols"] = doc.get("symbols", []) + new_rows
    text = ledger_io.dump(doc, header=HEADER)
    with open(ledger_path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"Appended {len(new_rows)} symbol rows to MIGRATION_LEDGER.yml")
    return len(new_rows)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build seed MIGRATION_LEDGER.yml")
    parser.add_argument("--cpp", default=os.path.join(DEFAULT_ROOT, "cpp_symbol_manifest.json"))
    parser.add_argument("--rust", default=os.path.join(DEFAULT_ROOT, "rust_symbol_manifest.json"))
    parser.add_argument("--out", default=os.path.join(DEFAULT_ROOT, "MIGRATION_LEDGER.yml"))
    parser.add_argument("--stdout", action="store_true", help="Print to stdout instead of writing --out")
    parser.add_argument(
        "--include-dir",
        metavar="DIR",
        default=None,
        help=(
            "Append symbols from a C++ subdirectory (relative to forgottenserver/src, "
            "e.g. src/http) to cpp_symbol_manifest.json and MIGRATION_LEDGER.yml "
            "without rebuilding the whole ledger."
        ),
    )
    args = parser.parse_args(argv)

    if args.include_dir:
        added = _append_include_dir(
            cpp_manifest_path=args.cpp,
            ledger_path=args.out,
            rust_manifest_path=args.rust,
            include_dir=args.include_dir,
        )
        print(f"--include-dir done: {added} new ledger rows added.")
        return 0

    with open(args.cpp, "r", encoding="utf-8") as f:
        cpp_symbols = json.load(f)
    with open(args.rust, "r", encoding="utf-8") as f:
        rust_symbols = json.load(f)

    doc = build_doc(cpp_symbols, rust_symbols)
    text = ledger_io.dump(doc, header=HEADER)

    if args.stdout:
        sys.stdout.write(text)
    else:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote {len(doc['symbols'])} rows to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
