#!/usr/bin/env python3
"""Regenerate the file-level rollup from symbol-level ledger rows.

The rollup is the legacy view used by MIGRATION.md and external tooling:
one entry per C++ file, with the file-level status computed from its
symbol rows. Per design.md §11, the result is written back into
MIGRATION_LEDGER.yml under a `files:` key alongside `symbols:`.

File-level status logic:

  - DONE        — every row in the file has status in {migrated,
                  migrated_with_changes, intentionally_removed,
                  output_verified, obsolete}
  - PARTIAL     — at least one row has status in {partial, missing}
                  but no row is uncertain / needs_review.
  - PENDING     — at least one row has status in {uncertain,
                  needs_review} (audit not finished).
  - MISSING     — every row has status `missing` (rare; means the file
                  has no Rust counterpart at all).
  - NON_GOAL    — every row has `intentionally_removed` (the whole
                  file was deliberately not ported).

Usage:
    python3 scripts/ledger/rollup.py [--check]
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import Any

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import ledger_io  # noqa: E402

DEFAULT_ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir))


def _file_status(statuses: set[str]) -> str:
    if statuses & {"uncertain", "needs_review"}:
        return "PENDING"
    if statuses & {"partial"}:
        return "PARTIAL"
    if statuses & {"missing"} and not (statuses & {"migrated", "migrated_with_changes", "output_verified"}):
        if statuses <= {"missing"}:
            return "MISSING"
        return "PARTIAL"
    if statuses <= {"intentionally_removed"}:
        return "NON_GOAL"
    if statuses <= {"migrated", "migrated_with_changes", "intentionally_removed", "output_verified", "obsolete"}:
        return "DONE"
    return "PARTIAL"


def build_rollup(symbols: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_file: dict[str, list[dict[str, Any]]] = {}
    for row in symbols:
        f = row.get("cpp", {}).get("file", "")
        by_file.setdefault(f, []).append(row)

    out: list[dict[str, Any]] = []
    for f in sorted(by_file):
        rows = by_file[f]
        statuses = {r.get("status", "uncertain") for r in rows}
        confs = {r.get("confidence", "low") for r in rows}
        out.append({
            "cpp": f,
            "status": _file_status(statuses),
            "symbol_count": len(rows),
            "statuses": sorted(statuses),
            "confidence": "high" if confs == {"high"} else ("low" if "low" in confs else "medium"),
        })
    return out


HEADER = """\
MIGRATION_LEDGER.yml — per-symbol migration audit (authoritative)

Generated by scripts/ledger/build_seed.py + scripts/ledger/rollup.py.
DO NOT EDIT the cpp.* fields by hand. The files: rollup is regenerated
from the symbols list by rollup.py; do not edit it directly.

Schema and rules: see openspec/changes/forgottenserver-migration-ledger-
symbol-audit/design.md.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate files: rollup")
    parser.add_argument("--ledger", default=os.path.join(DEFAULT_ROOT, "MIGRATION_LEDGER.yml"))
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the existing files: rollup differs from the regenerated one")
    args = parser.parse_args(argv)

    with open(args.ledger, "r", encoding="utf-8") as f:
        doc = ledger_io.load(f.read())

    if doc.get("schema") != "per-symbol":
        print(f"ERROR: {args.ledger} is not schema=per-symbol")
        return 2

    new_files = build_rollup(doc.get("symbols", []))

    if args.check:
        existing = doc.get("files") or []
        if existing != new_files:
            print("files: rollup is out of date. Run without --check to regenerate.")
            diff_count = 0
            existing_by_cpp = {e.get("cpp"): e for e in existing}
            for nf in new_files:
                ef = existing_by_cpp.get(nf["cpp"])
                if ef != nf:
                    diff_count += 1
                    if diff_count <= 10:
                        print(f"  {nf['cpp']}: had={ef}, expected={nf}")
            print(f"Total drifted files: {diff_count}")
            return 1
        print(f"files: rollup is up to date ({len(new_files)} files)")
        return 0

    new_doc = {
        "version": doc.get("version", 2),
        "schema": "per-symbol",
        "last_updated": doc.get("last_updated"),
        "seed_source": doc.get("seed_source"),
        "files": new_files,
        "symbols": doc["symbols"],
    }
    with open(args.ledger, "w", encoding="utf-8") as f:
        f.write(ledger_io.dump(new_doc, header=HEADER))
    print(f"Regenerated files: rollup ({len(new_files)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
